apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
  labels:
    app: clinscriptum
    component: web
spec:
  replicas: {{ .Values.replicaCount.web }}
  selector:
    matchLabels:
      app: clinscriptum
      component: web
  template:
    metadata:
      labels:
        app: clinscriptum
        component: web
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.registry }}{{ .Values.image.web.repository }}:{{ .Values.image.web.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "https://{{ (index .Values.ingress.hosts 0).host }}/trpc"
          resources:
            {{- toYaml .Values.resources.web | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
spec:
  type: {{ .Values.service.web.type }}
  ports:
    - port: {{ .Values.service.web.port }}
      targetPort: 3000
  selector:
    app: clinscriptum
    component: web
